# Changes here will be overwritten by Copier
_commit: v2.3.1
_src_path: harmon-init
bunch_add: true
devcontainer: false
git_init: true
github_collaboration_templates: true
github_release_init: true
github_remote_create: true
license: mit
obsidian_project_add: false
project_description: My personal developer kit of code templates, boilerplates,
    scripts, and AI assets.
project_name: Harmon DevKit
project_slug: harmon-devkit
project_url: None
run_task_bootstrap: false
run_task_install: false
